parser: babel-eslint

extends: [airbnb, plugin:jest/recommended, prettier]

env:
    browser: true
    node: true

rules:
    no-underscore-dangle: off
    no-plusplus: [error, {allowForLoopAfterthoughts: true}]
    no-use-before-define: [error, {variables: false}]
    no-console: off

    react/jsx-filename-extension: [warn, {extensions: [.js]}]
    react/jsx-indent: off
    react/jsx-one-expression-per-line: off
    react/destructuring-assignment: off
    react/prop-types: off
