language: node_js

node_js:
  - 8

sudo: false

before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash
  - export PATH="$HOME/.yarn/bin:$PATH"

install:
  - npm i -g codecov

cache:
  yarn: true
  directories:
    - ".eslintcache"
    - "node_modules"

script:
  - yarn prepublishOnly
  - codecov --disable=gcov
